anfisa_for_friends/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('', views.description, name='description'),
]

anfisa_for_friends/anfisa_for_friends/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('homepage.urls', namespace='homepage')),
    path('about/', include('about.urls', namespace='about')),
    path('ice_cream/', include('ice_cream.urls', namespace='ice_cream')),
    path('admin/', admin.site.urls),
]

anfisa_for_friends/homepage/urls.py
from django.urls import path

from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name='index'),
]

anfisa_for_friends/ice_cream/urls.py
from django.urls import path

from . import views

app_name = 'ice_cream'

urlpatterns = [
    path('', views.ice_cream_list, name='ice_cream_list'),
    path('<int:pk>/', views.ice_cream_detail, name='ice_cream_detail'),
]

anfisa_for_friends/about/models.py
from django.db import models

# Create your models here.

anfisa_for_friends/homepage/models.py
from django.db import models

# Create your models here.

anfisa_for_friends/ice_cream/models.py
from django.db import models

# Create your models here.

anfisa_for_friends/about/views.py
from django.shortcuts import render


def description(request):
    template = 'about/description.html'
    return render(request, template)

anfisa_for_friends/homepage/views.py
from django.shortcuts import render


def index(request):
    template = 'homepage/index.html'
    return render(request, template)

anfisa_for_friends/ice_cream/views.py
from django.shortcuts import render

ice_cream_catalog = [
    {
        'id': 0,
        'title': 'Классический пломбир',
        'description': 'Настоящее мороженое, для истинных ценителей вкуса. '
                       'Если на столе появляется пломбир — это не надолго.',
    },
    {
        'id': 1,
        'title': 'Мороженое с кузнечиками',
        'description': 'В колумбийском стиле: мороженое '
                       'с добавлением настоящих карамелизованных кузнечиков.',
    },
    {
        'id': 2,
        'title': 'Мороженое со вкусом сыра чеддер',
        'description': 'Вкус настоящего сыра в вафельном стаканчике.',
    },
]


def ice_cream_detail(request, pk):
    template = 'ice_cream/detail.html'
    context = {'ice_cream': ice_cream_catalog[pk]}
    return render(request, template, context)


def ice_cream_list(request):
    template = 'ice_cream/list.html'
    context = {'ice_cream_list': ice_cream_catalog}
    return render(request, template, context)

anfisa_for_friends/templates/about/description.html
{% extends "base.html" %}
{% block title %}
  Анфиса для друзей. О проекте
{% endblock %}
{% block content %}
  <h1 class="pb-2 mb-0">О проекте</h1>
  <p>
    Каталог экзотических сортов мороженого.
  </p>
{% endblock %}

anfisa_for_friends/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru"> 
  <head>    
    <meta charset="utf-8"> 
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'img/fav/fav.ico' %}" type="image">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>
      {% block title %}Анфиса для друзей.{% endblock %}
    </title>
  </head>
  <body>
    {% include "includes/header.html" %}
    <main class="pt-5 my-5">       
      <div class="container">
      {% block content %}{% endblock %}
      </div>
    </main>
    {% include "includes/footer.html" %}   
  </body>
  <script src="{% static "js/jquery-3.2.1.slim.min.js" %}"></script>
  <script src="{% static "js/bootstrap.min.js" %}"></script>
</html>

anfisa_for_friends/templates/homepage/index.html
{% extends "base.html" %}
{% block title %}
  Анфиса для друзей. Главная
{% endblock %}
{% block content %} 
  <h1 class="pb-2 mb-0">Главная страница</h1>
  <div class="border-top text-center py-5">
  </div>
{% endblock %}

anfisa_for_friends/templates/ice_cream/detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}
  Анфиса для друзей. Подробное описание мороженого
{% endblock %}
{% block content %}
  <h1>Подробное описание мороженого</h1>
  <h3>{{ ice_cream.title }}</h3>
  <p>{{ ice_cream.description }}</p>
  <div class="col-12 col-md-6 mb-3">
    <img class="img-fluid"
    height="400" width="300"
    src="{% static 'img/image-holder.png' %}">      
  </div>
{% endblock %}
 

anfisa_for_friends/templates/ice_cream/list.html
{% extends "base.html" %}
{% load static %}
{% block title %}
  Анфиса для друзей. Каталог мороженого
{% endblock %}
{% block content %}
  <h1 class="pb-2 mb-0">Каталог мороженого</h1>
    <div class="row">
    {% for ice_cream in ice_cream_list %}
        <h3>{{ ice_cream.title }}</h3>
        <p>{{ ice_cream.description|truncatewords:10 }}</p>
        <a href="{% url 'ice_cream:ice_cream_detail' ice_cream.id %}">подробнее</a>
        <hr>
    {% endfor %}
{% endblock %}

anfisa_for_friends/templates/includes/footer.html
{% load static %}
<footer class="border-top text-center py-3">
  <p>© 2022 «MyKit Corp»</p>
</footer>

anfisa_for_friends/templates/includes/header.html
{% load static %}
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top shadow-sm">
    <div class="container">
      <div 
        class="navbar-toggler" 
        type="button" 
        data-toggle="collapse" 
        data-target="#navbarNav" 
        aria-controls="navbarNav" 
        aria-expanded="false" 
        aria-label="Toggle navigation"
        >
        <span class="navbar-toggler-icon"></span>
      </div>
      <div class="collapse navbar-collapse" id="navbarNav">
      {% with request.resolver_match.view_name as view_name %}
        <ul class="nav nav-pills">
          <li class="nav-item">
            <a 
              class="nav-link {% if view_name  == 'homepage:index' %}active{% endif %}"
              href="{% url 'homepage:index' %}"
              >
              Главная
            </a>
          </li>
          <li class="nav-item">
            <a 
              class="nav-link {% if view_name  == 'ice_cream:ice_cream_list' %}active{% endif %}"
              href="{% url 'ice_cream:ice_cream_list' %}"
              >
              Каталог мороженого
            </a> 
          </li>
          <li class="nav-item">
            <a 
              class="nav-link {% if view_name  == 'about:description' %}active{% endif %}"
              href="{% url 'about:description' %}"
              >
              О проекте
            </a>
          </li>
        {% endwith %}
        </ul>
      </div> 
      <a class="navbar-brand" href="index.html">
        <img class="d-inline-block align-top"
        height="50"
        src="{% static 'img/logo.png' alt=""%}"> 
      </a>         
    </div>
  </nav>
</header>